module.exports = {
    // App Settings
    NODE_PORT: process.env.NODE_PORT || 3000,
    NODE_IP: process.env.NODE_IP || '0.0.0.0',
    MONGO_URI: process.env.MONGO_URI || 'mongodb://localhost/authllizer',
    TOKEN_SECRET: process.env.TOKEN_SECRET || 'YOUR_UNIQUE_JWT_TOKEN_SECRET',

    // OAuth 2.0
    BITBUCKET_SECRET: process.env.BITBUCKET_SECRET || 'YOUR_BITBUCKET_CLIENT_SECRET',
    FACEBOOK_SECRET: process.env.FACEBOOK_SECRET || 'YOUR_FACEBOOK_CLIENT_SECRET',
    FOURSQUARE_SECRET: process.env.FOURSQUARE_SECRET || 'YOUR_FOURSQUARE_CLIENT_SECRET',
    GITHUB_SECRET: process.env.GITHUB_SECRET || 'YOUR_GITHUB_CLIENT_SECRET',
    GOOGLE_SECRET: process.env.GOOGLE_SECRET || 'YOUR_GOOGLE_CLIENT_SECRET',
    INSTAGRAM_SECRET: process.env.INSTAGRAM_SECRET || 'YOUR_INSTAGRAM_CLIENT_SECRET',
    LINKEDIN_SECRET: process.env.LINKEDIN_SECRET || 'YOUR_LINKEDIN_CLIENT_SECRET',
    LIVE_SECRET: process.env.LIVE_SECRET || 'YOUR_LIVE_CLIENT_SECRET',
    REDDIT_SECRET: process.env.REDDIT_SECRET || 'YOUR_REDDIT_CLIENT_SECRET',
    SPOTIFY_SECRET: process.env.SPOTIFY_SECRET || 'YOUR_SPOTIFY_CLIENT_SECRET',
    TWITCH_SECRET: process.env.TWITCH_SECRET || 'YOUR_TWITCH_CLIENT_SECRET',
    VK_SECRET: process.env.VK_SECRET || 'YOUR_VK_CLIENT_SECRET',
    WORDPRESS_SECRET: process.env.WORDPRESS_SECRET || 'YOUR_WORDPRESS_CLIENT_SECRET',
    YAHOO_SECRET: process.env.YAHOO_SECRET || 'YOUR_YAHOO_CLIENT_SECRET',

    // OAuth 1.0
    TWITTER_KEY: process.env.TWITTER_KEY || 'YOUR_TWITTER_CUSTOMER_KEY',
    TWITTER_SECRET: process.env.TWITTER_SECRET || 'YOUR_TWITTER_CUSTOMER_SECRET'
};
